name: React Native CI Build

on:
  push:
    branches:
      - main

jobs:
  android_build:
    name: Android Build (AAB)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install JS dependencies
        run: npm install

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant Gradle permissions
        run: chmod +x android/gradlew

      - name: Build Android Release Bundle (AAB)
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload Android AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab

  ios_build:
    name: iOS Build (Archive)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install JS dependencies
        run: npm install

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS Archive
        run: |
          cd ios
          xcodebuild -workspace YourApp.xcworkspace \
                     -scheme YourApp \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $RUNNER_TEMP/YourApp.xcarchive \
                     archive

      - name: Export IPA (Optional)
        run: |
          cd ios
          xcodebuild -exportArchive \
                     -archivePath $RUNNER_TEMP/YourApp.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $RUNNER_TEMP/ipa_output

      - name: Upload iOS IPA Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: ${{ runner.temp }}/ipa_output/*.ipa
